import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.filechooser.FileSystemView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dilan
 */
public class ShareGUI extends javax.swing.JPanel {

    /**
     * Creates new form ShareGUI
     */
    
    String location = "./Sharable_Files/";
    
    public ShareGUI() {
        
        ArrayList<String> sharedFiles = new ArrayList<>();
        //Reading shared files from the folder
        File folder = new File(location);
        if (! folder.exists()){
            folder.mkdir();
            // If you require it to make the entire directory path including parents,
            // use directory.mkdirs(); here instead.
        }
        
        
        initComponents();
        
        DefaultListModel model = new DefaultListModel();
        
        File[] listOfFiles = folder.listFiles();
        
        if( listOfFiles != null){
            for (File listOfFile : listOfFiles) {
                if (listOfFile.isFile()) {
                    sharedFiles.add(listOfFile.getName());
                }
            }
        }
        
        model.addAll(sharedFiles);
        lstSharedFiles = new JList<>(model);
        jScrollPane1.setViewportView(lstSharedFiles);
        lstSharedFiles.setLayoutOrientation(JList.VERTICAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFileShare = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSharedFiles = new javax.swing.JList<>();
        btnFileRemove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Share Files");

        btnFileShare.setText("Add File");
        btnFileShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileShareActionPerformed(evt);
            }
        });

        lstSharedFiles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstSharedFiles);

        btnFileRemove.setText("Remove File");
        btnFileRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileRemoveActionPerformed(evt);
            }
        });

        jLabel2.setText("My Shared Files");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnFileShare, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnFileRemove))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFileShare)
                    .addComponent(btnFileRemove))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileShareActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 
  
            // invoke the showsSaveDialog function to show the save dialog 
        int r = fileChooser.showDialog(null, "Select");
        
        if (r == JFileChooser.APPROVE_OPTION){ 
            
            try {
                String x = fileChooser.getSelectedFile().getAbsolutePath();
                
                Path copy = Files.copy(Paths.get(x), Paths.get(this.location + fileChooser.getSelectedFile().getName()));
                
                this.refreshView();
                
            } catch (IOException ex) {
                System.out.println("Failed to copy. Check the Priviledges of file directory");
            }
        } 
    }//GEN-LAST:event_btnFileShareActionPerformed

    private void btnFileRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileRemoveActionPerformed
        try {
           
            List<String> selected = this.lstSharedFiles.getSelectedValuesList();
            
            for (String item:selected){
                Files.delete(Paths.get(this.location+ item));
            }
            
            this.refreshView();

            
        } catch (IOException ex) {
            Logger.getLogger(ShareGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnFileRemoveActionPerformed

    public void refreshView(){
        
        ArrayList<String> sharedFiles = new ArrayList<>();
        File folder = new File(this.location);
        File[] listOfFiles = folder.listFiles();
        
        if( listOfFiles != null){
            for (File listOfFile : listOfFiles) {
                if (listOfFile.isFile()) {
                    sharedFiles.add(listOfFile.getName());
                }
            }
        }
        
        DefaultListModel listModel = (DefaultListModel) lstSharedFiles.getModel();
        listModel.removeAllElements();
        listModel.addAll(sharedFiles);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFileRemove;
    private javax.swing.JButton btnFileShare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstSharedFiles;
    // End of variables declaration//GEN-END:variables
}
